TRUNCATE TABLE job_post RESTART IDENTITY AND COMMIT NO CHECK;
TRUNCATE TABLE users RESTART IDENTITY AND COMMIT NO CHECK;
TRUNCATE TABLE job_package RESTART IDENTITY AND COMMIT NO CHECK;
TRUNCATE TABLE post_zone RESTART IDENTITY AND COMMIT NO CHECK;
TRUNCATE TABLE contract RESTART IDENTITY AND COMMIT NO CHECK;
TRUNCATE TABLE review RESTART IDENTITY AND COMMIT NO CHECK;
INSERT INTO users(user_id, user_name, user_email,user_password, user_phone, user_is_active) VALUES (DEFAULT, 'Francisco Quesada','password', 'franquesada@gmail.com', '1147895678', true);
INSERT INTO users(user_id, user_name, user_email,user_password, user_phone, user_is_active) VALUES (DEFAULT, 'Manuel Rodriguez', 'manurodriguez@gmail.com','password', '1109675432', true);
INSERT INTO users(user_id, user_name, user_email,user_password, user_phone, user_is_active) VALUES (DEFAULT, 'Gonzalo Arca', 'gonzaarca@gmail.com','password', '0549940406521', true);
INSERT INTO users(user_id, user_name, user_email,user_password, user_phone, user_is_active) VALUES (DEFAULT, 'Manuel Parma', 'manuparma@gmail.com','password', '1158586363', true);
INSERT INTO job_post(post_id, user_id, post_title, post_available_hours, post_job_type, post_is_active) VALUES (DEFAULT, 1, 'Electricista Matriculado', 'Lun a Viernes 10hs - 14hs', 1, true);
INSERT INTO post_zone(post_id, zone_id) VALUES (1, 1);
INSERT INTO post_zone(post_id, zone_id) VALUES (1, 2);
INSERT INTO job_package(package_id, post_id, package_title, package_description, package_price, package_rate_type, package_is_active) VALUES (DEFAULT, 1, 'Trabajo Simple', 'Arreglos de tomacorrientes', 200.00, 0, true);
INSERT INTO job_package(package_id, post_id, package_title, package_description, package_price, package_rate_type, package_is_active) VALUES (DEFAULT, 1, 'Trabajo no tan simple', 'Instalacion de cableado electrico', 850.00, 0, true);
INSERT INTO contract(contract_id, client_id, package_id, creation_date, contract_description) VALUES (DEFAULT, 2, 1, NOW(), 'Se me rompio una zapatilla');
INSERT INTO contract(contract_id, client_id, package_id, creation_date, contract_description) VALUES (DEFAULT, 4, 1, NOW(), 'Arreglo de fusibles');
INSERT INTO job_post(post_id, user_id, post_title, post_available_hours, post_job_type, post_is_active) VALUES (DEFAULT, 4, 'Plomero Matriculado', 'Miercoles a Viernes 10hs - 14hs', 2, true);
INSERT INTO post_zone(post_id, zone_id) VALUES (2, 3);
INSERT INTO job_package(package_id, post_id, package_title, package_description, package_price, package_rate_type, package_is_active) VALUES (DEFAULT, 2, 'Trabajo Complejo', 'Arreglos de canerias', 500.00, 0, true);
INSERT INTO contract(contract_id, client_id, package_id, creation_date, contract_description) VALUES (DEFAULT, 3, 3, NOW(), 'Se me rompieron las tuberias del banio');
INSERT INTO contract(contract_id, client_id, package_id, creation_date, contract_description) VALUES (DEFAULT, 2, 3, NOW(), 'Se me rompio una tuberia en la cocina');
INSERT INTO contract(contract_id, client_id, package_id, creation_date, contract_description) VALUES (DEFAULT, 3, 2, NOW(), 'Instalacion de tomacorrientes');
INSERT INTO review(contract_id, review_rate, review_title, review_description) VALUES (1, 4, 'Muy bueno', 'Resolvio todo en cuestion de minutos');
INSERT INTO review(contract_id, review_rate, review_title, review_description) VALUES (2, 2, 'Medio pelo', 'Resolvio todo de forma ideal');
COMMIT;