import { themeUtils } from '../theme';

const contractCardStyles = (theme) => ({
  contractCard: {
    boxShadow: themeUtils.shadows.containerShadow,
  },
  contractTitle: {
    fontSize: '1.2rem',
    fontWeight: 700,
    width: '100%',
    WebkitLineClamp: 2,
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    overflowWrap: 'break-word',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  stateContainer: {
    display: 'flex',
    justifyContent: 'start',
    alignItems: 'center',
    width: '100%',
    color: 'white',
    fontSize: '0.9rem',
    fontWeight: 500,
    padding: '10px 10px',
  },
  avatarSize: {
    height: 40,
    width: 40,
  },
  jobType: {
    color: themeUtils.colors.blue,
    fontSize: '0.9rem',
    fontWeight: 600,
  },
  fieldLabel: {
    color: themeUtils.colors.grey,
    fontSize: '0.8rem',
    fontWeight: 500,
    marginBottom: 5,
  },
  jobImageContainer: {
    position: 'relative',
    marginBottom: 20,
    [theme.breakpoints.up('sm')]: {
      marginBottom: 30,
    },
    display: 'flex',
    justifyContent: 'center',
  },
  scheduledDateContainer: {
    position: 'absolute',
    bottom: -20,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '0.8rem',
    textAlign: 'center',
    padding: '5px 15px',
    backgroundColor: themeUtils.colors.lightBlue,
    boxShadow: themeUtils.shadows.containerShadow,
    borderRadius: 25,
    color: 'white',
  },
  jobImage: {
    borderRadius: 10,
    height: 170,
    width: 170,
    [theme.breakpoints.down('sm')]: {
      width: '100%',
    },
    objectFit: 'cover',
  },
  scheduledDate: {
    fontSize: '1.3rem',
    fontWeight: 600,
    lineHeight: '1.2rem',
  },
  scheduledTime: {
    fontSize: '1.1rem',
    fontWeight: 600,
    lineHeight: '1.2rem',
  },
  userContainer: {
    display: 'flex',
    alignItems: 'center',
    width: '40%',
  },
  username: {
    width: '80%',
    lineHeight: '1.2rem',
    fontWeight: 600,
    WebkitLineClamp: 2,
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    overflowWrap: 'break-word',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    marginLeft: 10,
  },
  contractActions: {
    display: 'flex',
    width: '100%',
    justifyContent: 'flex-end',
    padding: 7,
  },
  timesHired: {
    'backgroundColor': '#f5f5f5',
    'borderRadius': '18px',
    'color': 'gray',
    'padding': '6px 12px',
    'margin': '2px',
    'marginTop': '2px',
    'textAlign': 'center',
    'lineHeight': '1',
    'width': 'max-content',
  },
  detailsModalBody: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    color: 'black',
    padding: '10px 20px',
    height: 450,
    overflowY: 'scroll',
    overflowX: 'none',
  },
  detailsHeaderContainer: {
    display: 'flex',
    width: '100%',
    margin: '30px 0 10px 0',
    alignItems: 'center',
  },
  detailsHeader: {
    fontSize: themeUtils.fontSizes.base,
    marginLeft: 10,
    fontWeight: 600,
  },
  detailsImage: {
    height: 300,
    width: 500,
    objectFit: 'contain',
    borderRadius: 10,
    backgroundColor: themeUtils.colors.blue,
    boxShadow: themeUtils.shadows.containerShadow,
  },
  detailsDescription: {
    backgroundColor: themeUtils.colors.lightGrey,
    fontSize: '0.9rem',
    fontWeight: 500,
    width: '100%',
    padding: 10,
    borderRadius: 10,
    boxShadow: themeUtils.shadows.containerShadow,
  },
  contactField: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: 10,
    width: 300,
  },
  contactFieldValue: {
    color: 'white',
    textAlign: 'right',
    fontWeight: 600,
    WebkitLineClamp: 3,
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    overflowWrap: 'break-word',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    width: '80%',
  },
  contactIcon: {
    height: 50,
    width: 50,
    color: 'white',
  },
  ratingContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: themeUtils.colors.yellow,
    padding: 15,
    borderRadius: 10,
  },
  ratingInput: {
    fontSize: '0.9rem',
    fontWeight: 500,
  },
  ratingLabel: {
    fontSize: '1rem',
    fontWeight: 600,
    marginTop: 20,
    marginBottom: 5,
  },
  reviewRescheduleContainer: {
    display: 'flex',
    padding: 20,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  calendarTop: {
    backgroundColor: themeUtils.colors.red,
    boxShadow: themeUtils.shadows.containerShadow,
  },
  calendarBody: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    backgroundColor: 'white',
    boxShadow: themeUtils.shadows.containerShadow,
    borderRadius: '0 0 10px 10px',
  },
  calendarDate: {
    fontSize: '2rem',
    fontWeight: 700,
  },
  calendarTime: {
    fontSize: '1.3rem',
    fontWeight: 600,
  },
  disclaimerIcon: {
    fontSize: '3rem',
    color: themeUtils.colors.yellow,
  },
  rescheduleDisclaimer: {
    marginTop: 20,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '0.9rem',
    fontWeight: 500,
    borderRadius: 15,
    border: '2px solid ' + themeUtils.colors.yellow,
    padding: 10,
    boxShadow: themeUtils.shadows.containerShadow,
  },
  packageContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    backgroundColor: themeUtils.colors.blue,
    borderRadius: 5,
    color: 'white',
    fontWeight: 600,
    padding: 10,
    boxShadow: themeUtils.shadows.containerShadow,
  },
  packageTitle: {
    WebkitLineClamp: 3,
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    overflowWrap: 'break-word',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '100%',
  },
  priceContainer: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: 'white',
    color: themeUtils.colors.blue,
    borderRadius: 10,
    padding: 5,
  },
  fillInput: {
    backgroundColor: 'rgba(0, 0, 0, 0.09)',
    width: '100%',
    padding: '5px',
  },
  centerDatePicker: {
    '& > div': {
      display: 'flex',
      justifyContent: 'center',
    },
  },
});

export default contractCardStyles;
