ALTER TABLE contract
ADD COLUMN IF NOT EXISTS image_data BYTEA,
ADD COLUMN IF NOT EXISTS contract_image_type VARCHAR;

CREATE TABLE IF NOT EXISTS post_image
(
	image_id		SERIAL 	PRIMARY KEY,
	post_id			INTEGER NOT NULL,
	image_data		BYTEA 	NOT NULL,
	image_type		VARCHAR NOT NULL,
	FOREIGN KEY (post_id) REFERENCES job_post ON DELETE CASCADE
);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS user_image BYTEA,
ADD COLUMN IF NOT EXISTS image_type VARCHAR;

ALTER TABLE post_image
ADD COLUMN IF NOT EXISTS image_type VARCHAR NOT NULL default 'unknown';
