const categoryImageMap = new Map();
categoryImageMap.set(0, process.env.PUBLIC_URL + '/img/plumbing.jpeg');
categoryImageMap.set(1, process.env.PUBLIC_URL + '/img/electrician.jpeg');
categoryImageMap.set(2, process.env.PUBLIC_URL + '/img/carpentry.jpeg');
categoryImageMap.set(3, process.env.PUBLIC_URL + '/img/catering.png');
categoryImageMap.set(4, process.env.PUBLIC_URL + '/img/painter.jpeg');
categoryImageMap.set(5, process.env.PUBLIC_URL + '/img/teaching.jpeg');
categoryImageMap.set(6, process.env.PUBLIC_URL + '/img/cleaning.png');
categoryImageMap.set(7, process.env.PUBLIC_URL + '/img/babysitting.jpeg');
export default categoryImageMap;
